### ISSUE TITLE
Can't import with tilda path to a file

### ISSUE THREAD

**Issue by nesterone** [Krasnyanskiy/jrsh#154]
$> import ~/Downloads/slow_report_export.zip 
Neither a file nor a directory
usage: import [file]
$>

**Comment by Krasnyanskiy** [comment]
It is indeed a bug. Thanks.

**Comment by Krasnyanskiy** [comment]
Now it works fine with `Export` and `Import` operations.

**Comment by nesterone** [comment]
Hi, 

Where I can download last version ?


Thanks,
Igor N.

**Comment by Krasnyanskiy** [comment]
You can download it from [here](https://github.com/Krasnyanskiy/jrsh/releases).
