### ISSUE TITLE
UX issue (export command)

### ISSUE THREAD

**Issue by Krasnyanskiy** [Krasnyanskiy/jrsh#82]
Do you think I should show parameter hints to the user when he presses **TAB** key after **path** input?
```bash
>>> export repo "/public/Samples/NewTestFolder/Report" [TAB]
with-users   with-events
```
Or maybe it is better to show parameter hints with direction
```bash
>>> export repo "/public/Samples/NewTestFolder/Report" [TAB]
to   with-users   with-events
```
Which one should I choose?

**Comment by nesterone** [comment]
What means 'to' ?

**Comment by Krasnyanskiy** [comment]
It is a direction.

**Comment by nesterone** [comment]
it`s ok
